/**
 * Created by abyss http://www.abyssss.com
 *
 * The ww is the abbreviation of Words to World Front Animation Engine.
 * The ww makes animation based special script generated by Rei.
 * So, the 'world' ww shows, which is very simple now, is the simulate world in Rei's 'mind'.
 *
 * It uses three.js for 3D works, tween.js for animation and something else for control.
 *
 */

var WW = { REVISION: '1' };
